test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,8 +38,12 @@ jobs:
           kubectl get all -n httpbin
           kubectl wait --for=condition=Ready pod -l app=httpbin -n httpbin --timeout=300s
           POD_NAME=$(kubectl get pods -l app=httpbin -n httpbin -o jsonpath='{.items[0].metadata.name}')
-          kubectl exec -n httpbin "$POD_NAME" -- curl -s -f http://localhost:80/get || {
-            echo "❌ GET request failed. httpbin Deployment is not running"
+          kubectl run test-curl \
+            --image=curlimages/curl:latest \
+            --rm -i --restart=Never \
+            --timeout=60s \
+            -- curl -s -f "http://$POD_NAME.httpbin.svc.cluster.local/get" || {
+            echo "❌ GET request failed"
             exit 1
           }
 
